export const EXEC_SEARCH = 'EXEC_SEARCH';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const STORE_FETCHED_FILMS = 'STORE_FETCHED_FILMS';
export const SELECT_FILM = 'SELECT_FILM';
export const SEARCH_FILMS = 'SEARCH_FILMS';
export const RETURN_TO_SEARCHBOX = 'RETURN_TO_SEARCHBOX';
