export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';
export const CHANGE_SORTING_CRITERION = 'CHANGE_SORTING_CRITERION';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
export const RECEIVE_FILMS = 'RECEIVE_FILMS';
