export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';
export const RECEIVE_FILMS = 'RECEIVE_FILMS';
export const REQUEST_FILMS = 'REQUEST_FILMS';
export const UPDATE_QUERY_PARAMETER = 'UPDATE_QUERY_PARAMETER';
export const CHANGE_PAGINATION_INDEX = 'CHANGE_PAGINATION_INDEX';
export const RETURN_TO_SEARCH = 'RETURN_TO_SEARCH';
export const STORE_CURRENT_FILM = 'STORE_CURRENT_FILM';
export const GET_FILM_BY_ID = 'GET_FILM_BY_ID';
